name:                histogram-extras
version:             0.2.2.0
github:              "cspollard/histogram-extras"
license:             BSD3
author:              "Chris Pollard"
maintainer:          "cspollard@gmail.com"
copyright:           "2019 Chris Pollard"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/test#readme>


dependencies:
- base
- bifunctors
- lens
- hashable
- linear
- vector
- profunctors
- text
- cereal
- cereal-text
- containers
- cereal-vector
- profunctor-hep

library:
  source-dirs: src
  ghc-options: -Wall
