name:                histogram-extras
version:             0.2.2.0
github:              "cspollard/histogram-extras"
license:             BSD3
author:              "Chris Pollard"
maintainer:          "cspollard@gmail.com"
copyright:           "2019 Chris Pollard"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/test#readme>


default-extensions:
- RankNTypes
- ScopedTypeVariables
- TupleSections
- DerivingVia
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveGeneric
- PatternSynonyms

dependencies:
- base
- cereal-text
- bifunctors
- semialign
- these
- semigroupoids
- lens
- linear
- profunctors
- text
- cereal
- containers
- hashable
- unordered-containers
- keys
- variation
- moore

library:
  source-dirs: src
  ghc-options: -Wall -O2
