flags: {}
extra-package-dbs: []
packages:
- '.'

- location:
    git: https://github.com/cspollard/profunctor-hep.git
    commit: 7ae0ade9ba30d51fbe7a4ca052b75aec7f2f38de
  extra-dep: true

extra-deps:
- extensible-0.5.1    
- membership-0    
- trivial-constraint-0.6.0.0    
- functor-combinators-0.1.1.1    


resolver: lts-13.25

