flags: {}
extra-package-dbs: []
packages:
- '.'

- location:
    git: https://github.com/cspollard/profunctor-hep.git
    commit: 6bd72b243fde7a0097ed4650d6b2c1541078e063
  extra-dep: true

extra-deps:
- extensible-0.5.1    
- membership-0    
- trivial-constraint-0.6.0.0    
- functor-combinators-0.1.1.1    


resolver: lts-13.25

