flags: {}
extra-package-dbs: []
packages:
- '.'

- location:
    git: https://github.com/cspollard/profunctor-hep.git
    commit: 88dcb7b4ee58d50cbfb4840d3e61d49d18979c8b
  extra-dep: true

extra-deps:
- extensible-0.5.1    
- membership-0    
- trivial-constraint-0.6.0.0    
- functor-combinators-0.1.1.1    


resolver: lts-13.25

