flags: {}
extra-package-dbs: []
packages:
- '.'
- '/Users/cspollard/Programming/profunctor-hep.git'

  # - location:
  #     git: https://github.com/cspollard/profunctor-hep.git
  #     commit: 7ae0ade9ba30d51fbe7a4ca052b75aec7f2f38de
  #   extra-dep: true

extra-deps:
- extensible-0.5.1    
- membership-0    

resolver: lts-13.25

